# Generated by Django 4.1.3 on 2022-11-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('bwritter', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sroll', models.CharField(max_length=100)),
                ('sdept', models.CharField(max_length=100)),
                ('bname', models.CharField(max_length=100)),
                ('bissn', models.CharField(max_length=15)),
                ('bwritter', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'issuebook',
            },
        ),
    ]
