# Generated by Django 4.1.3 on 2022-11-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_issuebook_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
